#!/usr/bin/perl

BEGIN { unshift @INC, '/usr/local/cpanel'; }

use strict;
use warnings;

use XML::Simple;
use Cpanel::WildcardDomain      ();
my $xml;

while (<STDIN>) {
       $xml .= $_;
}

my $xml_hashed = XMLin($xml);
my $domain =  "$xml_hashed->{'cpanelevent'}->{'params'}->{'domain'}";

$domain =~ s/_/./g;

if (Cpanel::WildcardDomain::is_wildcard_domain($domain)) {
   $domain = Cpanel::WildcardDomain::encode_wildcard_domain($domain);
}

unlink "/usr/local/nginx/vhost/$domain" . ".conf";
system("/etc/init.d/nginx restart");

