#!/usr/bin/perl 

BEGIN { unshift @INC, '/usr/local/cpanel'; }

use Cpanel::ApacheBooster;
use IO::Select;
use JSON::Syck;
use Data::Dumper;


my $username = get_passed_data();

if (-f '/var/cpanel/users/' . $username) {
  my $main_domain = Cpanel::ApacheBooster::get_domain_by_username($username);
  my $sub_domains = Cpanel::ApacheBooster::get_subdomain($username);
  if ($main_domain) {
    system("/scripts/createvhost.pl $main_domain");
    if (scalar(@{$sub_domains})) {
      foreach my $subdomain (@{$sub_domains}) {
        system("/scripts/createvhost.pl $subdomain");
      }
    }
  }
}

sub get_passed_data {
    my $raw_data   = '';
    my $input_data = {};
    my $selects    = IO::Select->new();
    $selects->add( \*STDIN );
    if ( $selects->can_read(.1) ) {
        while (<STDIN>) {
            $raw_data .= $_;
        }
        $input_data = JSON::Syck::Load($raw_data);
    }
    my $user_name = $input_data->{data}->{user};
    return $user_name;
}


