#!/usr/bin/perl


my $option = $ARGV[0];
my $value  = $ARGV[1];

if (("$option" eq '-cs') && (defined $value)) {
  update_static_ttl($value);
}
elsif (("$option" eq '-cd') && (defined $value)) {
  update_dynamic_ttl($value);
}
elsif (("$option" eq '-cb') && (defined $value)) {
  update_sysconfig($value);
}
else {
  print "Invalid option\n";
}

sub update_static_ttl {
  my $value = shift;
  my $file = '/usr/local/varnish/etc/varnish/static_file.vcl';
  #remve unwanted char from value
  $value =~ s/[^0-9a-zA-Z]//g;
  $value =~ tr/A-Z/a-z/;
  if (($value =~ /[0-9a-z]/i) && ($value =~ /[A-Za-z]/)) {
    open(my $FH, '>', $file) or die $!;
    print $FH "set beresp.ttl = $value;";
    close($FH);
  }
}

sub update_dynamic_ttl {
  my $value = shift;
  my $file = '/usr/local/varnish/etc/varnish/dynamic_file.vcl';
  #remve unwanted char from value
  $value =~ s/[^0-9a-zA-Z]//g;
  $value =~ tr/A-Z/a-z/;
  if (($value =~ /[0-9a-z]/i) && ($value =~ /[A-Za-z]/)) {
    open(my $FH, '>', $file) or die $!;
    print $FH "set beresp.ttl = $value;";
    close($FH);
  }
}

sub update_sysconfig {
  my $value = shift;
  my $file = '/etc/sysconfig/varnish';
  $value =~ s/[^0-9a-zA-Z]//g;
  $value =~ tr/a-z/A-Z/;
  if (($value =~ /[0-9A-Z]/i) && ($value =~ /[A-Za-z]/)) {
    my $old_value = get_sys_value();
    open(my $FH, '<', $file) or die $!;
    my @content = <$FH>;
    close($HF);
    my @file_opts;
    foreach my $line (@content) {
      $line =~ s/$old_value/$value/g if $line =~ /DAEMON_OPTS=(.*)/;
      push(@file_opts, $line);
    }
    open(my $FILE, '>', $file) or die $!;
    print $FILE @file_opts;
    close($FILE);
  }
}


sub get_sys_value {
  my $file = '/etc/sysconfig/varnish';
  open(my $FH, '<', $file) or die $!;
  my @content = <$FH>;
  close($HF);
  my $bin_val;
  foreach $line (@content) {
    next unless $line =~ /DAEMON_OPTS=(.*)/;
    my @split = split('\-s(.*),', $line );
    $bin_val = $split[2];
    $bin_val =~ s/[^0-9A-Z]//g;
  }
  return  $bin_val;
}

