#!/usr/bin/perl


my $option = $ARGV[0];

print get_sys_value() if $option eq '-b';
print get_static_ttl() if $option eq '-d';
print get_dynamic_ttl() if $option eq '-f';

sub get_sys_value {
  my $file = '/etc/sysconfig/varnish';
  open(my $FH, '<', $file) or die $!;
  my @content = <$FH>;
  close($HF);
  my $bin_val;
  foreach $line (@content) {
    next unless $line =~ /DAEMON_OPTS=(.*)/;
    my @split = split('\-s(.*),', $line );
    print Dumper @split;
    $bin_val = $split[2];
    $bin_val =~ s/[^0-9A-Z]//g;
  }
  return  $bin_val;
}

sub get_static_ttl {
  my $file = '/usr/local/varnish/etc/varnish/static_file.vcl';
  open(my $FH, '<', $file) or die $!;
  my $content = <$FH>;
  close($HF);
  my (undef, $ttl) = split('=', $content );
  $ttl =~ s/[^0-9a-z]//g;
  return $ttl;
}

sub get_dynamic_ttl {
    my $file = '/usr/local/varnish/etc/varnish/dynamic_file.vcl';
  open(my $FH, '<', $file) or die $!;
  my $content = <$FH>;
  close($HF);
  my (undef, $ttl) = split('=', $content );
  $ttl =~ s/[^0-9a-z]//g;
  return $ttl;
}

