#!/usr/local/cpanel/3rdparty/bin/perl

use strict; 
use Cpanel::ApacheBooster       ();

my $input = $ARGV[0];
my $username;

if ($input =~ ".lock" ) {
    ($username = $input) =~ s/\.\w{4}$//;   
} else {
   $username = $input;
}

if (-f '/var/cpanel/users/' . $username) {
  my $main_domain = Cpanel::ApacheBooster::get_domain_by_username($username);
  my $sub_domains = Cpanel::ApacheBooster::get_subdomain($username);
  if ($main_domain) {
    system("/scripts/createvhost.pl $main_domain");
    if (scalar(@{$sub_domains})) {
      foreach my $subdomain (@{$sub_domains}) {
        system("/scripts/createvhost.pl $subdomain");
      }
    }
  }
}
