#!/bin/bash
# apachebooster - installmod-rpf                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited

HTTPD_VER=`/usr/local/apache/bin/httpd -v| grep "Server version:"|cut -d "/" -f2|awk '{print $1}'|cut -d "." -f1,2`

if [ "$HTTPD_VER" != "2.4" ]; then
   /scripts/installmodrpaf
else
  /scripts/installmodreverseproxy
fi

