#!/bin/bash

# apachebooster - installmod-rpf                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited

CUDIR=`pwd`
cd /usr/local/src
rm -rf mod_remoteip*
wget https://svn.apache.org/repos/asf/httpd/httpd/trunk/modules/metadata/mod_remoteip.c

if [ ! -e 'mod_remoteip.c' ]; then
  wget http://prajith.in/downloads/mod_remoteip.c
fi

/usr/local/apache/bin/apxs -i -c -n mod_remoteip.so mod_remoteip.c


if grep "mod_rpaf.conf"  /usr/local/apache/conf/includes/pre_main_global.conf ; then
  if [ -f "/usr/local/apache/conf/mod_rpaf.conf" ]; then
    rm -rf /usr/local/apache/conf/mod_rpaf.conf
  fi
  /scripts/rebuildippool > /dev/null 2>&1
  LIST=$(/scripts/ipusage | awk '{print $1}' | while read ip; do echo -ne "RemoteIPInternalProxy ${ip}\n"; done)
  cat > /usr/local/apache/conf/mod_rpaf.conf << EOF
LoadModule remoteip_module modules/mod_remoteip.so
<IfModule remoteip_module>
RemoteIPHeader X-Real-IP
RemoteIPInternalProxy 127.0.0.1
$LIST
</IfModule>
EOF

else
  /scripts/rebuildippool > /dev/null 2>&1
  LIST=$(/scripts/ipusage | awk '{print $1}' | while read ip; do echo -ne "RemoteIPInternalProxy ${ip}\n"; done)
  cat > /usr/local/apache/conf/mod_rpaf.conf << EOF
LoadModule remoteip_module modules/mod_remoteip.so
<IfModule remoteip_module>
#Mod_remoteip settings
RemoteIPHeader X-Real-IP
RemoteIPInternalProxy 127.0.0.1
$LIST
</IfModule>
EOF
  echo "Include \"/usr/local/apache/conf/mod_rpaf.conf\""  >> /usr/local/apache/conf/includes/pre_main_global.conf
fi
/etc/init.d/httpd restart


