#!/usr/local/cpanel/3rdparty/bin/perl

BEGIN { unshift @INC, '/usr/local/cpanel', '/scripts/'; }

use Cpanel::ApacheBooster       ();
use Cpanel::DIp                 ();
use Cpanel::WildcardDomain      ();

my $tpl_file = '/usr/local/varnish/etc/varnish/exclude.vhost.tpl';

my $main_ip     = Cpanel::DIp::getmainip();

if (-e "$tpl_file") {
 open (MYFILE, '<', $tpl_file) or die $!;
 while (<MYFILE>) {
   chomp;
   next if $_ =~ m/^\s*(?:#.*)?$/;
   my $vhost = "$_";
   chomp $vhost;
   $vhost =~ s/\r//g;
   exclude_nginx_vhost($vhost);
 }
 close (MYFILE);
}



sub exclude_nginx_vhost {
  my $domain_name = shift;
  my $domain_hash = Cpanel::ApacheBooster::single_domain_hash($domain_name);
  my $IP_PORT     = $domain_hash->{ip};
  if ((not $IP_PORT) || ($main_ip eq $IP_PORT)) {
    $IP_PORT = '80';
  }
  else {
    $IP_PORT = $IP_PORT . ':80';
  }
  if (Cpanel::WildcardDomain::is_wildcard_domain($domain_hash->{domain})) {
    $domain_hash->{domain_alias} = $domain_hash->{domain};
    $domain_hash->{domain}       = Cpanel::WildcardDomain::encode_wildcard_domain($domain_hash->{domain});
  }
  vhost_template($IP_PORT,
      $domain_hash->{domain},
      $domain_hash->{domain_alias},
      $domain_hash->{documentroot},
      $domain_hash->{ip});
}


sub vhost_template {
    my ($listen, $main_domain, $domain_alias, $document_root, $domain_ip) = @_;
    my $conf = <<CONFIG;
server {
   access_log off;
   error_log  logs/vhost-error_log warn;
   listen $listen;
   server_name $main_domain $domain_alias;
   root $document_root;
   location / {
        proxy_pass http://$domain_ip:8082;
        include proxy.inc;
   }
   location ~ /\.ht {
        deny all;
   }
}
CONFIG
  if (open(my $file, '>/usr/local/nginx/vhost/' . $main_domain . ".conf")) {
    print($file $conf);
    close $file;
  } else {
    print "Unable to create virtual host entry for $main_domain\n";
  }
}

