#!/usr/bin/perl
# apachebooster - postwwwacct                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited


my %OPTS = @ARGV;
$DOMAIN = "$OPTS{'domain'}";
chomp $DOMAIN;
system ("/scripts/createvhost.pl $DOMAIN");
system("/etc/init.d/nginx restart");
