#!/usr/local/cpanel/3rdparty/bin/perl
# apachebooster - postwwwacct                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited

use IO::Select;
use JSON::Syck;
use Data::Dumper;


my $DOMAIN = get_passed_data();
chomp $DOMAIN;

if ($DOMAIN) {
    system ("/scripts/createvhost.pl $DOMAIN");
    system("/etc/init.d/nginx restart");
}


sub get_passed_data {
    my $raw_data   = '';
    my $input_data = {};
    my $selects    = IO::Select->new();
    $selects->add( \*STDIN );
    if ( $selects->can_read(.1) ) {
        while (<STDIN>) {
            $raw_data .= $_;
        }
        $input_data = JSON::Syck::Load($raw_data);
    }
    my $data_var = $input_data->{'data'};
    my $domain =  $data_var->{'domain'};
    return $domain;
}
