#!/usr/local/cpanel/3rdparty/bin/perl

# apachebooster - prekillacct                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited

use Cpanel::ApacheBooster;
use IO::Select;
use JSON::Syck;
use Data::Dumper;


my $username = get_passed_data();

if (-f '/var/cpanel/users/' . $username) {
  my $main_domain = Cpanel::ApacheBooster::get_domain_by_username($username);
  my $sub_domains = Cpanel::ApacheBooster::get_subdomain($username);
  if ($main_domain) {
    my $domain_conf = '/usr/local/nginx/vhost/' . $main_domain . '.conf';
    unlink("$domain_conf") if -e $domain_conf;
    if (scalar(@{$sub_domains})) {
      foreach my $subdomain (@{$sub_domains}) {
        if (Cpanel::WildcardDomain::is_wildcard_domain($subdomain)) {
           $subdomain = Cpanel::WildcardDomain::encode_wildcard_domain($subdomain);
        }
        my $domain_conf = '/usr/local/nginx/vhost/' . $subdomain . '.conf';
        unlink("$domain_conf") if -e $domain_conf;
      }
    }
  }
}


sub get_passed_data {
    my $raw_data   = '';
    my $input_data = {};
    my $selects    = IO::Select->new();
    $selects->add( \*STDIN );
    if ( $selects->can_read(.1) ) {
        while (<STDIN>) {
            $raw_data .= $_;
        }
        $input_data = JSON::Syck::Load($raw_data);
    }
    my $username = $input_data->{data}->{user};
    return $username;
}
1;
