#!/usr/local/cpanel/3rdparty/bin/perl

# apachebooster - prekillacct                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited

use Cpanel::ApacheBooster;
use IO::Select;
use JSON::Syck;
use Data::Dumper;

my $user_name = get_passed_data();

if ($user_name) {
  my $domain_name = Cpanel::ApacheBooster::get_domain_by_username($user_name);
  if ($domain_name) {
    unlink "/usr/local/nginx/vhost/" . $domain_name . ".conf";
    system("/etc/init.d/nginx restart");
  }
}

sub get_passed_data {
    my $raw_data   = '';
    my $input_data = {};
    my $selects    = IO::Select->new();
    $selects->add( \*STDIN );
    if ( $selects->can_read(.1) ) {
        while (<STDIN>) {
            $raw_data .= $_;
        }
        $input_data = JSON::Syck::Load($raw_data);
    }
    my $username = $input_data->{data}->{user};
    return $username;
}

