#!/bin/bash
# apachebooster - rebuildvhost                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited
echo "This script is deprecated and dangerous to use in almost all circumstances.\n";
exit 0;
rebuildvhost() {
UA=`/scripts/whmapi.pl --sa`
for i in $UA
do

RESULT=$(/scripts/whmapi.pl --gd  $i)
if [ "$RESULT" ]; then
IP=`echo "$RESULT"|grep "IP"|cut -d: -f2`
USER=`echo "$RESULT"|grep ^USER|cut -d: -f2`
DOMAIN=`echo "$RESULT"|grep ^DOMAIN|cut -d: -f2`
ROOT=`echo "$RESULT"|grep ^DOCUMENTROOT|cut -d: -f2`
ALIAS=`echo "$RESULT"|grep ^ALIAS|cut -d: -f2`
if [ ! -d /usr/local/nginx/vhost ]; then
mkdir /usr/local/nginx/vhost
fi
cat > "/usr/local/nginx/vhost/$DOMAIN.conf" << EOF
server {
access_log off;
error_log  logs/vhost-error_log warn;
listen    80;
server_name $DOMAIN $ALIAS;
location ~* ^.+.(jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|iso|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|mp3|ogv|ogg|flv|swf|mpeg|mpg|mpeg4|mp4|avi|wmv|js|css)$ {
        expires 7d;
            error_page  404 = @custom;
            error_page  500 = @inerror;
        root $ROOT;
        access_log /usr/local/apache/domlogs/$DOMAIN;
        log_not_found  off;
        }
location ~ /\.ht {
          deny all;
        }

location / {
        log_not_found  off;

  client_max_body_size    2000m;
  client_body_buffer_size 512k;
  proxy_next_upstream error;
  proxy_send_timeout   400;
  proxy_read_timeout   400;
  proxy_buffer_size    32k;
  proxy_buffers     16 32k;
  proxy_busy_buffers_size 64k;
  proxy_temp_file_write_size 64k;
  proxy_connect_timeout 400s;

        proxy_redirect  http://www.$DOMAIN:8082   http://www.$DOMAIN;
        proxy_redirect  http://$DOMAIN:8082   http://$DOMAIN;
        proxy_pass   http://$IP:8082/;
        proxy_set_header   Host   \$host;
        proxy_set_header   X-Real-IP  \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        }

location @custom {
        internal;

  client_max_body_size    2000m;
  client_body_buffer_size 512k;
  proxy_next_upstream error;
  proxy_send_timeout   400;
  proxy_read_timeout   400;
  proxy_buffer_size    32k;
  proxy_buffers     16 32k;
  proxy_busy_buffers_size 64k;
  proxy_temp_file_write_size 64k;
  proxy_connect_timeout 400s;

        proxy_redirect  http://www.$DOMAIN:8082   http://www.$DOMAIN;
        proxy_redirect  http://$DOMAIN:8082   http://$DOMAIN;
        proxy_pass   http://$IP:8082;
        proxy_set_header   Host   \$host;
        proxy_set_header   X-Real-IP  \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        }
        
location @inerror {
        internal;

  client_max_body_size    2000m;
  client_body_buffer_size 512k;
  proxy_next_upstream error;
  proxy_send_timeout   400;
  proxy_read_timeout   400; 
  proxy_buffer_size    32k;
  proxy_buffers     16 32k;
  proxy_busy_buffers_size 64k;
  proxy_temp_file_write_size 64k;
  proxy_connect_timeout 400s;

        proxy_redirect  http://www.$DOMAIN:8082   http://www.$DOMAIN;
        proxy_redirect  http://$DOMAIN:8082   http://$DOMAIN;
        proxy_pass   http://$IP:8082;
        proxy_set_header   Host   \$host;
        proxy_set_header   X-Real-IP  \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        }
 


}


EOF
fi
done
}
createvhost() {
KEY=$1
RESULT=$(/scripts/whmapi.pl --gd  $1)
if [ "$RESULT" == "" ]; then
echo "Domain not exists"
exit 0
fi
IP=`echo "$RESULT"|grep "IP"|cut -d: -f2`
USER=`echo "$RESULT"|grep ^USER|cut -d: -f2`
DOMAIN=`echo "$RESULT"|grep ^DOMAIN|cut -d: -f2`
ROOT=`echo "$RESULT"|grep ^DOCUMENTROOT|cut -d: -f2`
ALIAS=`echo "$RESULT"|grep ^ALIAS|cut -d: -f2`
if [ ! -d /usr/local/nginx/vhost ]; then
mkdir /usr/local/nginx/vhost
fi
cat > "/usr/local/nginx/vhost/$DOMAIN.conf" << EOF
server {
access_log off;
error_log  logs/vhost-error_log warn;
listen    80;
server_name $DOMAIN $ALIAS;
location ~* ^.+.(jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|iso|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|mp3|ogv|ogg|flv|swf|mpeg|mpg|mpeg4|mp4|avi|wmv|js|css)$ {
        expires 7d;
            error_page  404 = @custom;
            error_page  500 = @inerror;
        root $ROOT;
        access_log /usr/local/apache/domlogs/$DOMAIN;
        log_not_found  off;
        }
location ~ /\.ht {
          deny all;
        }

location / {
        log_not_found  off;

  client_max_body_size    2000m;
  client_body_buffer_size 512k;
  proxy_next_upstream error;
  proxy_send_timeout   400;
  proxy_read_timeout   400;
  proxy_buffer_size    32k;
  proxy_buffers     16 32k;
  proxy_busy_buffers_size 64k;
  proxy_temp_file_write_size 64k;
  proxy_connect_timeout 400s;

        proxy_redirect  http://www.$DOMAIN:8082   http://www.$DOMAIN;
        proxy_redirect  http://$DOMAIN:8082   http://$DOMAIN;
        proxy_pass   http://$IP:8082/;
        proxy_set_header   Host   \$host;
        proxy_set_header   X-Real-IP  \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        }

location @custom {
        internal;

  client_max_body_size    2000m;
  client_body_buffer_size 512k;
  proxy_next_upstream error;
  proxy_send_timeout   400;
  proxy_read_timeout   400;
  proxy_buffer_size    32k;
  proxy_buffers     16 32k;
  proxy_busy_buffers_size 64k;
  proxy_temp_file_write_size 64k;
  proxy_connect_timeout 400s;

        proxy_redirect  http://www.$DOMAIN:8082   http://www.$DOMAIN;
        proxy_redirect  http://$DOMAIN:8082   http://$DOMAIN;
        proxy_pass   http://$IP:8082;
        proxy_set_header   Host   \$host;
        proxy_set_header   X-Real-IP  \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        }
        
location @inerror {
        internal;

  client_max_body_size    2000m;
  client_body_buffer_size 512k;
  proxy_next_upstream error;
  proxy_send_timeout   400;
  proxy_read_timeout   400; 
  proxy_buffer_size    32k;
  proxy_buffers     16 32k;
  proxy_busy_buffers_size 64k;
  proxy_temp_file_write_size 64k;
  proxy_connect_timeout 400s;

        proxy_redirect  http://www.$DOMAIN:8082   http://www.$DOMAIN;
        proxy_redirect  http://$DOMAIN:8082   http://$DOMAIN;
        proxy_pass   http://$IP:8082;
        proxy_set_header   Host   \$host;
        proxy_set_header   X-Real-IP  \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        }
 


}


EOF
}
nginx_status() {
cat > "/usr/local/nginx/vhost/localhost.conf" << EOF
server {
access_log off;
listen    80;
server_name localhost 127.0.0.1;
 location = /extended_status {
        extended_status on;
    }
location = /nginx_status {
stub_status on;
  access_log   off;
}
}
EOF
}


if [ "$1" == "" ]; then
rebuildvhost
nginx_status
else
createvhost $1
nginx_status
fi
/usr/local/nginx/sbin/nginx -t

