#!/bin/bash
# apachebooster - rebuildngixconf                            Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
# prajithpalakkuda@gmail.com                                       http://ndimensionz.com http://esupports.net
# This code is subject to the GPL  license. Unauthorized copying is prohibited

cat > "/usr/local/nginx/conf/nginx.conf" <<EOF
user  nobody;
worker_processes  2;
error_log  logs/error.log info;
timer_resolution 100ms;
worker_rlimit_nofile  8192;
events {
worker_connections  5120; 
use epoll; 
}
http {

open_file_cache max=5000 inactive=30s;
open_file_cache_valid 120s;
open_file_cache_min_uses 2;
open_file_cache_errors off;
open_log_file_cache max=1024 inactive=30s min_uses=2;

server_names_hash_max_size 10240;
server_names_hash_bucket_size 1024;
include    mime.types;
default_type  application/octet-stream;
sendfile on;
tcp_nopush on;
tcp_nodelay on;
keepalive_timeout  5;

gzip on;
gzip_vary on;
gzip_disable "MSIE [1-6]\.";
gzip_proxied any;
gzip_http_version 1.1;
gzip_min_length  1000;
gzip_comp_level  6;
gzip_buffers  16 8k;
gzip_types    text/plain text/xml text/css application/x-javascript application/xml image/png image/x-icon image/gif image/jpeg application/xml+rss text/javascript application/atom+xml application/javascript application/json;
ignore_invalid_headers on;
client_header_timeout  3m;
client_body_timeout 3m;
client_max_body_size 200m; 
send_timeout     3m;
connection_pool_size  256;
client_header_buffer_size 4k;
large_client_header_buffers 4 32k;
request_pool_size  4k;
output_buffers   4 32k;
postpone_output  1460;
proxy_temp_path  /tmp/nginx_proxy/;
include cloud_flare.conf;
log_format bytes_log "\$msec \$bytes_sent .";
include "/usr/local/nginx/vhost/*.conf";
include "/usr/local/nginx/conf/cpanel_autodiscover.conf";
}

EOF
/etc/init.d/httpd restart

