#!/bin/bash
/etc/init.d/varnish stop
/etc/init.d/nginx stop
ps aux|grep nginx|grep -v grep|awk '{print $2}'|xargs kill -9 
/scripts/preeasyapache
rm -rf /usr/local/nginx/
rm -rf /usr/local/varnish/

if [ -f "/usr/local/cpanel/whostmgr/cgi/addon_nginx.cgi" ]; then
   rm -rvf /usr/local/cpanel/whostmgr/cgi/addon_nginx.cgi
   rm -rvf /usr/local/cpanel/whostmgr/cgi/nginx
fi

if [ -f "/usr/local/cpanel/whostmgr/cgi/addon_ApacheBooster.cgi" -o -d "/usr/local/cpanel/whostmgr/cgi/ApacheBooster"  ]; then
   rm -rvf /usr/local/cpanel/whostmgr/cgi/addon_ApacheBooster.cgi
   rm -rvf /usr/local/cpanel/whostmgr/cgi/ApacheBooster
fi
#BEGIN scripts section

if [ -e "/scripts/installmodreverseproxy" ]; then
   rm -rvf /scripts/installmodreverseproxy
fi
if [ -e "/scripts/installmodremoteip" ]; then
   rm -rvf /scripts/installmodremoteip
fi
rm -rvf /scripts/postwwwacct_apachebooster
rm -rvf /scripts/installmod-rpf
rm -rvf /scripts/preeasyapache
rm -rvf /scripts/rebuildnginxconf
rm -rvf /scripts/rebuildvhost
rm -rvf /etc/init.d/nginx
rm -rvf /etc/init.d/varnish
rm -rvf /etc/sysconfig/varnish
rm -rvf /scripts/genevarnishconf
rm -rvf /scripts/purgecache
rm -rvf /scripts/purgedomains.php
rm -rvf /scripts/getfilettl
rm -rvf /scripts/adjustwrap
rm -rvf /scripts/varnishurlexlude
rm -rvf /scripts/prekillacct_apachebooster
rm -rvf /scripts/whmapi.pl
rm -rvf /scripts/updateapachebooster
rm -rvf /scripts/createvhost.pl
rm -rvf /scripts/installmodrpaf
rm -rvf /scripts/account_modify_pre_apachebooster
rm -rvf /scripts/account_modify_post_apachebooster
if [ -e "/scripts/ApacheBooster.pm" ]; then
   rm -rvf /scripts/ApacheBooster.pm
fi
if [ -e "/usr/local/cpanel/Cpanel/ApacheBooster.pm" ]; then
   rm -rvf /usr/local/cpanel/Cpanel/ApacheBooster.pm
fi
if [ -e "/scripts/incron_apachebooster" ]; then
   rm -rvf /scripts/incron_apachebooster
fi

sed -i '/nobody*/d' /etc/security/limits.d/90-nproc.conf
if [ -f "/etc/security/limits.conf.backup" ]; then
   mv -f  /etc/security/limits.conf.backup  /etc/security/limits.conf
fi

rm -rvf /scripts/restartsrv_varnish
rm -rvf /scripts/csf_fix.pl
rm -rvf /scripts/after_apache_make_install
#END scripts section

#BEGIN hooks
rm -rvf /usr/local/cpanel/hooks/addondomain/addaddondomain
rm -rvf /usr/local/cpanel/hooks/subdomain/addsubdomain
rm -rvf /usr/local/cpanel/hooks/addondomain/deladdondomain
rm -rvf /usr/local/cpanel/hooks/subdomain/delsubdomain
rm -rvf /usr/local/cpanel/hooks/park/park
rm -rvf /usr/local/cpanel/hooks/park/unpark
rm -rvf "/usr/local/cpanel/Cpanel/Config/ConfigObj/Driver/ApacheBooster*"
/usr/local/cpanel/bin/register_hooks
if [ -e "/usr/local/cpanel/bin/unregister_appconfig" ]; then
    /usr/local/cpanel/bin/unregister_appconfig ApacheBooster
else
    if [ -f "/var/cpane/apps/ApacheBooster.conf" ]; then
        rm -rf /var/cpane/apps/ApacheBooster.conf
    fi
fi

#END hooks

#BEGIN Apache Conf
sed -i  's/apache_port=0.0.0.0:82/apache_port=0.0.0.0:80/g'  /var/cpanel/cpanel.config
/usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings >/dev/null 2>&1
/scripts/rebuildhttpdconf
#END Apache Conf
if [ -f "/etc/munin/plugins/apache_accesses" ]; then
   sed -i 's/82/80/g' /etc/munin/plugins/apache_accesses /etc/munin/plugins/apache_processes /etc/munin/plugins/apache_volume
   `which service` munin-node restart >/dev/null 2>&1
fi

unset mv
cat /var/spool/cron/root | egrep -v "checkuserdomains|restartcheck|tmpwatch" > /tmp/cron.tmp
mv -f /tmp/cron.tmp /var/spool/cron/root
cat /var/spool/incron/root | egrep -v "incron_apachebooster|createvhost.pl|restartcheck" > /var/spool/incron/root

if [ -f "/usr/local/cpanel/bin/manage_hooks" ]; then
   /usr/local/cpanel/bin/manage_hooks  del script /scripts/postwwwacct_apachebooster --describe "Apachebooster" --category Whostmgr --event Accounts::Create --stage post >/dev/null 2>&1
   /usr/local/cpanel/bin/manage_hooks  del script /scripts/prekillacct_apachebooster --describe "Apachebooster" --category Whostmgr --event Accounts::Remove --stage pre >/dev/null 2>&1
   /usr/local/cpanel/bin/manage_hooks  del script /scripts/account_modify_post_apachebooster  --describe "Apachebooster" --category Whostmgr --event Accounts::Modify  --stage post >/dev/null 2>&1
   /usr/local/cpanel/bin/manage_hooks  del script /scripts/account_modify_pre_apachebooster  --describe "Apachebooster" --category Whostmgr --event Accounts::Modify  --stage pre >/dev/null 2>&1
fi

sed -i '/\/etc\/init.*.varnish/d' /etc/init.d/httpd
sed -i '/\/etc\/init.*.varnish/d' /usr/local/apache/bin/apachectl
sed -i '/\/etc\/init.*.nginx/d' /etc/init.d/httpd
sed -i '/\/etc\/init.*.nginx/d' /usr/local/apache/bin/apachectl

chkconfig apachebooster off
service incrond stop
chkconfig incrond off
/scripts/restartsrv_httpd
