#!/bin/bash
/etc/init.d/varnish stop
/etc/init.d/nginx stop
ps aux|grep nginx|grep -v grep|awk '{print $2}'|xargs kill -9 
/scripts/preeasyapache
rm -rf /usr/local/nginx/
rm -rf /usr/local/varnish/
rm -rvf /usr/local/cpanel/whostmgr/cgi/addon_nginx.cgi
rm -rvf /usr/local/cpanel/whostmgr/cgi/nginx
rm -rvf /scripts/postwwwacct
rm -rvf /scripts/installmod-rpf
rm -rvf /scripts/installnginx
rm -rvf /scripts/posteasyapache
rm -rvf /scripts/preeasyapache
rm -rvf /scripts/rebuildnginxconf
rm -rvf /scripts/rebuildvhost
rm -rvf /etc/ini.d/nginx
rm -rf /etc/init.d/varnish
rm -rvf /etc/sysconfig/varnish
rm -rvf /scripts/genevarnishconf
rm -rvf /scripts/purgecache
rm -rvf /scripts/purgedomains.php
rm -rvf /scripts/getfilettl
rm -rvf /scripts/adjustwrap
rm -rvf /scripts/rebuildvhost-bak
rm -rvf /scripts/varnishurlexlude
rm -rvf /scripts/prekillacct
rm -rvf /scripts/whmapi.pl
rm -rvf /scripts/updateapachebooster
rm -rvf /scripts/createvhost.pl
rm -rvf /scripts/ApacheBooster.pm
rm -rvf /scripts/restartsrv_varnish
rm -rvf /scripts/csf_fix.pl
               rm -rvf /usr/local/cpanel/hooks/addondomain/addaddondomain
               rm -rvf /usr/local/cpanel/hooks/subdomain/addsubdomain
               rm -rvf /usr/local/cpanel/hooks/addondomain/deladdondomain
               rm -rvf /usr/local/cpanel/hooks/subdomain/delsubdomain
               rm -rvf /usr/local/cpanel/hooks/park/park
               rm -rvf /usr/local/cpanel/hooks/park/unpark
/usr/local/cpanel/bin/register_hooks
sed -i  's/apache_port=0.0.0.0:82/apache_port=0.0.0.0:80/g'  /var/cpanel/cpanel.config
/usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings >/dev/null 2>&1
/scripts/rebuildhttpdconf
unset mv
cat /var/spool/cron/root | egrep -v "nginx_client" > /tmp/cron.tmp
mv -f /tmp/cron.tmp /var/spool/cron/root
cat /var/spool/incron/root | egrep -v "createvhost.pl|restartcheck" > /var/spool/incron/root
               /usr/local/cpanel/bin/manage_hooks  del script /scripts/postwwwacct --describe "Apachebooster" --category Whostmgr --event Accounts::Create --stage post >/dev/null 2>&1
               /usr/local/cpanel/bin/manage_hooks  del script /scripts/prekillacct --describe "Apachebooster" --category Whostmgr --event Accounts::Remove --stage pre >/dev/null 2>&1
sed -i '/\/etc\/init.*.varnish/d' /etc/init.d/httpd
sed -i '/\/etc\/init.*.varnish/d' /usr/local/apache/bin/apachectl
sed -i '/\/etc\/init.*.nginx/d' /etc/init.d/httpd
sed -i '/\/etc\/init.*.nginx/d' /usr/local/apache/bin/apachectl
chkconfig apachebooster off
/scripts/restartsrv_httpd
